[package]
name = "tool_mpi-macro"
version = "0.1.0"
authors = ["Matthias Kübrich <matthias.kuebrich@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "*"
syn = "*"